### ISSUE TITLE
make sure all packages needed are installed

### ISSUE THREAD

**Issue by remi-daigle** [remi-daigle/2017-CHONe-Data#9]
I'm making them install all the packages at the end of day 1 [here](https://github.com/remi-daigle/2017-CHONe-Data/blob/gh-pages/cleaning.Rmd#install-packages-for-tomorrow)

Please make sure all necessary packages as we write. I currently have
```
tidyverse
marmap
raster
sf
robis
```

cc @david-beauchesne

**Comment by david-beauchesne** [comment]
Add library calls after installs to spot any uninstalled packages

**Comment by david-beauchesne** [comment]
For package sf, might have a problem with xcode developer tools on mac. Here is a solution, to add to the install.packages section 
https://apple.stackexchange.com/questions/254380/macos-sierra-invalid-active-developer-path
